[[redirects]]
  from = "/pactober.html"
  to = "/pactober"
  status = 200
[[redirects]]
  from = "/birthday.html"
  to = "/birthday"
  status = 200
[[redirects]]
  from = "/pact_event_template.html"
  to = "/pact_event_template"
  status = 200
